renames the reverse style to inverse and fails when a style is applied to the background

diff --git a/colout b/colout
--- a/colout
+++ b/colout
@@ -54,7 +54,7 @@ echo -ne "Add colors to a text stream in your terminal.\n\n"\
   "  i[talic]\n"\
   "  u[nderline]\n"\
   "  blink,l\n"\
-  "  reverse,v\n"\
+  "  inverse,v\n"\
   "  h[idden]\n\n"\
   "  reset,rr\n"\
   "  r[eset_]bold,ro\n"\
@@ -62,7 +62,7 @@ echo -ne "Add colors to a text stream in your terminal.\n\n"\
   "  r[eset_]i[talic]\n"\
   "  r[eset_]u[nderline]\n"\
   "  r[eset_]blink,rl\n"\
-  "  r[eset_]reverse,rv\n"\
+  "  r[eset_]inverse,rv\n"\
   "  r[eset_]h[idden]\n\n"\
 " named colors (Note: an uppercase character is considered to be bold)\n"\
   "  default,none\n"\
@@ -437,18 +437,19 @@ fi
 declare -A style_names=(
   # styles
 
-  [fgnormal]=0 [fgbold]=1 [fgdim]=2 [fgitalic]=3 [fgunderline]=4 [fgblink]=5 [fgreverse]=7 [fghidden]=8
+  [fgnormal]=0 [fgbold]=1 [fgdim]=2 [fgitalic]=3 [fgunderline]=4 [fgblink]=5 [fginverse]=7 [fghidden]=8
   [fgn]=0 [fgo]=1 [fgd]=2 [fgi]=3 [fgu]=4 [fgl]=5 [fgv]=7 [fgh]=8
 
-  [bgnormal]=0 [bgbold]=1 [bgdim]=2 [bgitalic]=3 [bgunderline]=4 [bgblink]=5 [bgreverse]=7 [bghidden]=8
-  [bgn]=0 [bgo]=1 [bgd]=2 [bgi]=3 [bgu]=4 [bgl]=5 [bgv]=7 [bgh]=8
-
-  [fgreset]='21;22;23;24;25;26;27;28' [fgreset_bold]=21 [fgreset_dim]=22 [fgreset_italic]=23 [fgreset_underline]=24 [fgreset_blink]=25 [fgreset_reverse]=27 [fgreset_hidden]=28
+  [fgreset]='21;22;23;24;25;26;27;28' [fgreset_bold]=21 [fgreset_dim]=22 [fgreset_italic]=23 [fgreset_underline]=24 [fgreset_blink]=25 [fgreset_inverse]=27 [fgreset_hidden]=28
   [fgrr]='21;22;23;24;25;26;27;28' [fgro]=21 [fgrd]=22 [fgri]=23 [fgru]=24 [fgrl]=25 [fgrv]=27 [fgrh]=28
-  [fgreset_bold]=21 [fgrdim]=22 [fgritalic]=23 [fgrunderline]=24 [fgrblink]=25 [fgrreverse]=27 [fgrhidden]=28
+  [fgreset_bold]=21 [fgrdim]=22 [fgritalic]=23 [fgrunderline]=24 [fgrblink]=25 [fgrinverse]=27 [fgrhidden]=28
 
-  [bgnormal]=0 [bgbold]=1 [bgdim]=2 [bgitalic]=3 [bgunderline]=4 [bgblink]=5 [bgreverse]=7 [bghidden]=8
-  [bgn]=0 [bgo]=1 [bgd]=2 [bgi]=3 [bgu]=4 [bgl]=5 [bgv]=7 [bgh]=8
+  # [bgnormal]=0 [bgbold]=1 [bgdim]=2 [bgitalic]=3 [bgunderline]=4 [bgblink]=5 [bginverse]=7 [bghidden]=8
+  # [bgn]=0 [bgo]=1 [bgd]=2 [bgi]=3 [bgu]=4 [bgl]=5 [bgv]=7 [bgh]=8
+
+  # [bgreset]='21;22;23;24;25;26;27;28' [bgreset_bold]=21 [bgreset_dim]=22 [bgreset_italic]=23 [bgreset_underline]=24 [bgreset_blink]=25 [bgreset_inverse]=27 [bgreset_hidden]=28
+  # [bgrr]='21;22;23;24;25;26;27;28' [bgro]=21 [bgrd]=22 [bgri]=23 [bgru]=24 [bgrl]=25 [bgrv]=27 [bgrh]=28
+  # [bgreset_bold]=21 [bgrdim]=22 [bgritalic]=23 [bgrunderline]=24 [bgrblink]=25 [bgrinverse]=27 [bgrhidden]=28
 
 
   # foreground
@@ -560,7 +561,9 @@ set_default_colors() {
   append "$s"
 }
 invalid_style() {
-  echo "Invalid '$style' color." >&2
+  [ ! -z "${style_names[fg$style]}" ] &&
+    echo "'$style' style on a background is probably a mistake." >&2 ||
+    echo "Invalid '$style' color$extra." >&2
   exit 5
 }
 
