color map ; bold if color name is upper

diff --git a/colout b/colout
--- a/colout
+++ b/colout
@@ -260,21 +260,31 @@ declare -A style_names=(
   [bge8]=100 [bge9]=101 [bge10]=102 [bge11]=103 [bge12]=104 [bge13]=105 [bge14]=106 [bge15]=107
 )
 
-set_default_colors() {
-  append ';1;31'
-  append ';1;32'
-  append ';1;33'
-  append ';1;34'
-  append ';1;35'
-  append ';1;36'
-  append ';1;37'
-}
 
 cmd='38'
 prefix='fg'
 
+append_color_name() {
+  local c
+  for c in $@ ; do
+    append "$s;${style_names[$prefix$c]}"
+  done
+}
+append_color256() {
+  local c
+  for c in $@ ; do
+    append "$s;$cmd;5;$c"
+  done
+}
+append_color() {
+  local c
+  for c in $@ ; do
+    append "$s;$cmd;$c"
+  done
+}
+
 if [ $# = 0 ] ; then
-  set_default_colors
+  append_color {31..37}
 else
   while [ $# != 0 ] ; do
     # re-parse: "-- [-rg] [--] PATTERN [COLORS_AND_STYLES...]]..."
@@ -297,7 +307,7 @@ else
 
       rgx="$1"
       shift
-      [ $# = 0 ] && set_default_colors
+      [ $# = 0 ] && append_color {31..37}
 
       continue
     fi
@@ -306,14 +316,19 @@ else
     IFS=',=' read -a styles <<<"$1"
     s=''
     for style in "${styles[@]}" ; do
-      v=${style_names[$prefix$style]}
-      if [ -z "$v" ] ; then
-        # background selector
-        if [ bg = "$style" ] ; then
-          cmd='48'
-          prefix='bg'
-        else
-          if [[ "$style" =~ ^'#'[0-9a-fA-F]{6}$ ]] ; then
+      # background selector
+      if [ bg = "$style" ] ; then
+        cmd='48'
+        prefix='bg'
+      else
+        v=${style_names[$prefix$style]}
+        if [ -z "$v" ] ; then
+          v2=${style_names[$prefix${style,,}]}
+          # Bold and color
+          if [ ! -z "$v2" ] ; then
+            s+=";1;$v2"
+          # rgb888 hexadecimal color (#ffffff)
+          elif [[ "$style" =~ ^'#'[0-9a-fA-F]{6}$ ]] ; then
             rgb=$((16#${style:1}))
             s+=";$cmd;2;$(($rgb>>16));$((($rgb>>8)&0xff));$(($rgb&0xff))"
           # rgb444 hexadecimal color (#fff)
@@ -324,12 +339,22 @@ else
           elif [[ "$style" =~ ^'25'[0-5]$|^[0-2][0-4][0-9]$|^[0-9][0-9]$ ]] ; then
             s+=";$cmd;5;${style:1}"
           else
-            echo "Invalid '$style' color." >&2
-            exit 5
+            case "$style" in
+              rainbow) append_color_name \
+                m b c g y ; s+=";${style_names[${prefix}r]}" ;;
+              Rainbow) append_color256 \
+                92 93 57 21 27 33 39 45 51 50 49 48 47 46 82 118 154 190 226 220 214 208 202 ; s+="$s;$cmd;5;196" ;;
+              spectrum) append_color_name \
+                m b c w g y ; s+=";${style_names[${prefix}r]}" ;;
+              Spectrum) append_color256 \
+                91 92 56 57 21 27 26 32 31 37 36 35 41 40 41 77 83 84 120 121 157 194 231 254 255 231 230 229 228 227 226 220 214 208 202 ; s+="$s;$cmd;5;196" ;;
+              default|Default) append_color {31..36} ; s+="$s;$cmd;37" ;;
+              *) echo "Invalid '$style' color." >&2 ; exit 5 ;;
+            esac
           fi
+        else
+          s+=";$v"
         fi
-      else
-        s+=";$v"
         cmd='38'
         prefix='fg'
       fi
